name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Go
        uses: actions/setup-go@v5.3.0 
        with:
          go-version: '1.23.2'
          
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
