            - name: Setup Go environment
  uses: actions/setup-go@v5.3.0
  with:
    # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
    go-version: # optional
    # Path to the go.mod or go.work file.
    go-version-file: # optional
    # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
    check-latest: # optional
    # Used to pull Go distributions from go-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
    cache: # optional, default is true
    # Used to specify the path to a dependency file - go.sum
    cache-dependency-path: # optional
    # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
    architecture: # optional

            - name: Golangci-lint
  # You may pin to the exact commit or the version.
  # uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64
  uses: golangci/golangci-lint-action@v6.0.1
  with:
    # The version of golangci-lint to use.
When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.

    version: # optional
    # The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
    install-mode: # optional, default is binary
    # golangci-lint working directory, default is project root
    working-directory: # optional
    # the token is used for fetching patch of a pull request to show only new issues
    github-token: # optional, default is ${{ github.token }}
    # if set to true and the action runs on a pull request - the action outputs only newly found issues
    only-new-issues: # optional, default is false
    # if set to true then the all caching functionality will be complete disabled,
takes precedence over all other caching options.

    skip-cache: # optional, default is false
    # if set to true then the action will not save any caches, but it may still
restore existing caches, subject to other options.

    skip-save-cache: # optional, default is false
    # Force the usage of the embedded problem matchers
    problem-matchers: # optional, default is false
    # golangci-lint command line arguments
    args: # optional, default is 
    # Periodically invalidate a cache because a new code being added. (number of days)
    cache-invalidation-interval: # optional, default is 7
          
          
